library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(httr)
library(jsonlite)
library(rjson)
library(tidyverse)
library(data.table)
library(reshape2)
library(DT)
library(tidyverse)
library(ggfittext)
library(ggplot2)
library(ggrepel)
library(plotly)

Mammalia<-read.csv(file="/Users/mitaonaicha/Desktop/IUCN物种数据csv/Table\ 4a\ Animal\ species\ by\ class\ and\ order/4a-24MAMMALIA\ Animal\ species\ by\ class\ and\ order.csv",sep=",",header=T)
Amphibian<-read.csv(file="/Users/mitaonaicha/Desktop/IUCN物种数据csv/Table\ 4a\ Animal\ species\ by\ class\ and\ order/4a_2_Amphibian_Animal_species_by_class_order.csv",sep=",",header=T)
Reptilian<-read.csv(file="/Users/mitaonaicha/Desktop/IUCN物种数据csv/Table\ 4a\ Animal\ species\ by\ class\ and\ order/4a-31reptilia\ Animal\ species\ by\ class\ and\ order\ -\ REPTILIA.csv",sep=",",header=T)
Insecta<-read.csv(file="/Users/mitaonaicha/Desktop/IUCN物种数据csv/Table\ 4a\ Animal\ species\ by\ class\ and\ order/4a-22insecta_Animal\ species\ by\ class\ and\ order\ -\ INSECTA.csv",sep=",",header=T)
